export enum DemandStatus {
  CREATED = "CREATED",
  SUBMITTED = "SUBMITTED",
  IN_REVIEW = "IN_REVIEW",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
  CONTRACTED = "CONTRACTED",
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  CONFIRMED = "CONFIRMED",
}
