export enum OrderStatus {
  CREATED = "CREATED",
  CONFIRMED = "CONFIRMED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  INSPECTING = "INSPECTING",
  INSPECTED = "INSPECTED",
  COMPLETED = "COMPLETED",
}
